---
os: linux
dist: xenial
language: ruby
jobs:
  fast_finish: true
  include:
    - rvm: 2.4.1
    - rvm: 2.5
    - rvm: 2.7
    - rvm: 2.4.1
      script: bundle exec rubocop
notifications:
  email: false
